spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    #jdbc:h2:mem:testdb
    url: jdbc:h2:./data/db:NON_KEYWORDS=OFFSET
    driverClassName: org.h2.Driver
    username: h2user
    password: "p14h22"
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: embedded
      schema-locations: classpath:data/sql